---

name: Test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v3 
      with:
        version: 9 

    - name: Install deps
      run: pnpm i
      
    - name: Build
      run: pnpm build 

    - name: Lint
      run: pnpm lint
      
    - name: Test
      run: pnpm test
